/// <reference types="cypress" />

require('./version-check')
require('./map')
require('./map-invoke')
require('./tap')
require('./reduce')
require('./apply')
require('./primo')
require('./prop')
require('./at')
require('./print')
require('./table')
require('./invoke-once')
require('./update')
require('./partial')
require('./map-chain')
require('./find-one')
require('./to-plain-object')
require('./as-env')
require('./sample')
